-- Migrate RAG embeddings from 768 dims (Ollama nomic-embed-text) to 1024 dims
-- (NVIDIA-hosted baai/bge-m3, multilingual EN/ZH/MS).
--
-- Run ONCE in the Supabase dashboard → SQL Editor, then re-embed with
-- training-data/scripts/embed-and-upload.py. Old 768-dim vectors live in a
-- different space and cannot be reused, so we clear them first.

-- 1. Clear old chunks (they will be regenerated by the embed script)
truncate table tax_chunks;

-- 2. Resize the embedding column to 1024 dims
alter table tax_chunks alter column embedding type vector(1024);

-- 3. Recreate the similarity search function at 1024 dims.
--    Old signature took vector(768); drop it before creating the new one.
drop function if exists match_tax_chunks(vector(768), float, int);
drop function if exists match_tax_chunks(vector, float, int);

create or replace function match_tax_chunks(
  query_embedding vector(1024),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language sql stable
as $$
  select
    tax_chunks.id,
    tax_chunks.content,
    1 - (tax_chunks.embedding <=> query_embedding) as similarity
  from tax_chunks
  where 1 - (tax_chunks.embedding <=> query_embedding) > match_threshold
  order by tax_chunks.embedding <=> query_embedding
  limit match_count;
$$;

-- 4. Recreate the ANN index for the new dimension (cosine distance).
drop index if exists tax_chunks_embedding_idx;
create index tax_chunks_embedding_idx
  on tax_chunks using hnsw (embedding vector_cosine_ops);
