param(
  [string]$EnvPath = ".env.local"
)

$ErrorActionPreference = "Stop"

function Read-RequiredValue {
  param(
    [string]$Name,
    [string]$Prompt,
    [string]$DefaultValue = ""
  )

  while ($true) {
    if ($DefaultValue) {
      $value = Read-Host "$Prompt [$DefaultValue]"
      if (-not $value) {
        $value = $DefaultValue
      }
    } else {
      $value = Read-Host $Prompt
    }

    if ($value) {
      return $value.Trim()
    }

    Write-Host "$Name is required." -ForegroundColor Yellow
  }
}

function Format-DotEnvValue {
  param([string]$Value)

  $escaped = $Value.Replace("\", "\\").Replace('"', '\"').Replace("`r", "\r").Replace("`n", "\n")
  return '"' + $escaped + '"'
}

function Invoke-StripePost {
  param(
    [string]$SecretKey,
    [string]$Path,
    [hashtable]$Body
  )

  return Invoke-RestMethod `
    -Method Post `
    -Uri "https://api.stripe.com/v1/$Path" `
    -Headers @{ Authorization = "Bearer $SecretKey" } `
    -Body $Body `
    -ContentType "application/x-www-form-urlencoded"
}

function New-StripeCreditPrice {
  param(
    [string]$SecretKey,
    [string]$PackId,
    [string]$Name,
    [int]$AmountSen,
    [int]$Credits
  )

  $product = Invoke-StripePost `
    -SecretKey $SecretKey `
    -Path "products" `
    -Body @{
      name = "MYTax $Name Credits"
      description = "$Credits MYTax credits"
      "metadata[pack_id]" = $PackId
      "metadata[credits]" = "$Credits"
    }

  $price = Invoke-StripePost `
    -SecretKey $SecretKey `
    -Path "prices" `
    -Body @{
      currency = "myr"
      unit_amount = "$AmountSen"
      product = $product.id
      "metadata[pack_id]" = $PackId
      "metadata[credits]" = "$Credits"
    }

  return $price.id
}

function New-StripeWebhookEndpoint {
  param(
    [string]$SecretKey,
    [string]$AppUrl
  )

  $endpointUrl = $AppUrl.TrimEnd("/") + "/api/billing/stripe/webhook"

  return Invoke-StripePost `
    -SecretKey $SecretKey `
    -Path "webhook_endpoints" `
    -Body @{
      url = $endpointUrl
      "enabled_events[]" = "checkout.session.completed"
      description = "MYTax credits checkout fulfillment"
    }
}

Write-Host "Configure MYTax billing environment" -ForegroundColor Cyan
Write-Host "Secrets are written to $EnvPath and are not printed back." -ForegroundColor DarkGray
Write-Host ""

$supabaseUrl = Read-RequiredValue "NEXT_PUBLIC_SUPABASE_URL" "Supabase project URL"
$supabaseAnonKey = Read-RequiredValue "NEXT_PUBLIC_SUPABASE_ANON_KEY" "Supabase anon or publishable key"
$supabaseServiceRoleKey = Read-RequiredValue "SUPABASE_SERVICE_ROLE_KEY" "Supabase service role key"
$stripeSecretKey = Read-RequiredValue "STRIPE_SECRET_KEY" "Stripe secret key"
$stripePublishableKey = Read-RequiredValue "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" "Stripe publishable key"
$appUrl = Read-RequiredValue "NEXT_PUBLIC_APP_URL" "Public app URL" "https://mytaxs.online"

Write-Host ""
$createPrices = (Read-Host "Create Stripe prices for Starter/Pro/Business automatically? (y/N)").Trim().ToLowerInvariant()
if ($createPrices -eq "y" -or $createPrices -eq "yes") {
  Write-Host "Creating Stripe one-time prices..." -ForegroundColor Cyan
  $starterPrice = New-StripeCreditPrice -SecretKey $stripeSecretKey -PackId "starter" -Name "Starter" -AmountSen 900 -Credits 10
  $proPrice = New-StripeCreditPrice -SecretKey $stripeSecretKey -PackId "pro" -Name "Pro" -AmountSen 2900 -Credits 40
  $businessPrice = New-StripeCreditPrice -SecretKey $stripeSecretKey -PackId "business" -Name "Business" -AmountSen 7900 -Credits 120
} else {
  $starterPrice = Read-RequiredValue "STRIPE_PRICE_STARTER" "Stripe Starter price ID"
  $proPrice = Read-RequiredValue "STRIPE_PRICE_PRO" "Stripe Pro price ID"
  $businessPrice = Read-RequiredValue "STRIPE_PRICE_BUSINESS" "Stripe Business price ID"
}

Write-Host ""
$createWebhook = (Read-Host "Create Stripe webhook endpoint now? (Y/n)").Trim().ToLowerInvariant()
if (-not $createWebhook -or $createWebhook -eq "y" -or $createWebhook -eq "yes") {
  Write-Host "Creating Stripe webhook endpoint..." -ForegroundColor Cyan
  $webhook = New-StripeWebhookEndpoint -SecretKey $stripeSecretKey -AppUrl $appUrl
  $stripeWebhookSecret = $webhook.secret
} else {
  $stripeWebhookSecret = Read-RequiredValue "STRIPE_WEBHOOK_SECRET" "Stripe webhook signing secret"
}

$values = [ordered]@{
  NEXT_PUBLIC_SUPABASE_URL = $supabaseUrl
  NEXT_PUBLIC_SUPABASE_ANON_KEY = $supabaseAnonKey
  SUPABASE_SERVICE_ROLE_KEY = $supabaseServiceRoleKey
  STRIPE_SECRET_KEY = $stripeSecretKey
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = $stripePublishableKey
  STRIPE_WEBHOOK_SECRET = $stripeWebhookSecret
  STRIPE_PRICE_STARTER = $starterPrice
  STRIPE_PRICE_PRO = $proPrice
  STRIPE_PRICE_BUSINESS = $businessPrice
  NEXT_PUBLIC_APP_URL = $appUrl
}

$lines = @(
  "# Generated by scripts/configure-billing-env.ps1"
  "# Do not commit this file."
)

foreach ($entry in $values.GetEnumerator()) {
  $lines += "$($entry.Key)=$(Format-DotEnvValue $entry.Value)"
}

Set-Content -Path $EnvPath -Value ($lines -join [Environment]::NewLine) -Encoding utf8

Write-Host ""
Write-Host "Billing environment written to $EnvPath." -ForegroundColor Green
Write-Host "Webhook URL: $($appUrl.TrimEnd('/'))/api/billing/stripe/webhook" -ForegroundColor Green
